### ISSUE TITLE
Room participants changed event not triggered when a participant availability changes

### ISSUE THREAD

**Issue by valeriansaliou** [prose-im/prose-core-client#40]
After implementing `availability` from `participants` as specified in https://github.com/prose-im/prose-app-web/issues/28 I noticed that the `roomParticipantsChanged` event does not fire when eg. a private group member changes their availability (eg. unavailable to available, available to dnd, etc...).

UNLESS, they come `unavailable` from a non-`unavailable` availability, where the `roomParticipantsChanged` event fires as expected, and the view is updated correctly on my side.

Could we trigger `roomParticipantsChanged` whenever a `participant` changes their availability from any to any? That way I can update the list of participants w/ the correct availability.

**Comment by nesium** [comment]
Indeed. I'm currently firing a `contactChanged` event and `sidebarChanged` event if a DM conversation is affected. I'll have to iterate through the rooms to see where a participant is a member. Will changed that. The `any` to `unavailable` notification is fired since that is triggered by an 'affiliation changed' event from the MUC room.
